import { motion } from 'framer-motion';
import SEOHead from '@/components/seo/SEOHead';

export default function Terms() {
  return (
    <>
      <SEOHead
        title="Terms of Service"
        description="LexPilot AI Terms of Service. Read our terms governing the use of our AI-powered legal technology platform."
        canonical="/legal/terms"
      />

      <article style={{ paddingTop: 'calc(72px + 4rem)', paddingBottom: '4rem' }}>
        <div className="container-custom" style={{ maxWidth: '780px' }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
            <h1 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, letterSpacing: '-0.025em', marginBottom: '0.5rem' }}>Terms of Service</h1>
            <p style={{ color: '#6b7280', marginBottom: '2.5rem' }}>Last updated: 1 June 2026</p>

            <div style={{ fontSize: '1.05rem', lineHeight: 1.9, color: '#374151' }}>
              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>1. Acceptance of Terms</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                By accessing or using the LexPilot AI platform and services ("Services") provided by LexPilot AI Technologies Private Limited ("LexPilot AI", "we", "us"), you agree to be bound by these Terms of Service ("Terms"). If you are using the Services on behalf of an organisation, you represent that you have authority to bind that organisation to these Terms.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>2. Description of Services</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                LexPilot AI provides AI-powered legal technology tools including legal research, document drafting, contract review, compliance monitoring, and case management. Our Services are designed to assist legal professionals and are not a substitute for professional legal judgment.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>3. Account Responsibilities</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                You are responsible for maintaining the confidentiality of your account credentials. You must notify us immediately of any unauthorized access. You are responsible for all activities under your account. Each user must have a separate account; credential sharing is prohibited.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>4. Acceptable Use</h2>
              <p style={{ marginBottom: '1rem' }}>You agree not to:</p>
              <ul style={{ paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
                <li style={{ marginBottom: '0.75rem' }}>Use the Services for any unlawful purpose or to facilitate illegal activities.</li>
                <li style={{ marginBottom: '0.75rem' }}>Attempt to reverse engineer, decompile, or extract source code from our AI models.</li>
                <li style={{ marginBottom: '0.75rem' }}>Scrape, crawl, or use automated tools to extract data from the Services beyond API usage.</li>
                <li style={{ marginBottom: '0.75rem' }}>Share your account credentials or allow unauthorized third parties to access the Services.</li>
                <li style={{ marginBottom: '0.75rem' }}>Upload malicious software or content that could harm our infrastructure or other users.</li>
                <li style={{ marginBottom: '0.75rem' }}>Resell or redistribute the Services without a valid reseller agreement.</li>
              </ul>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>5. Intellectual Property</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                You retain ownership of all documents and data you upload to the platform. LexPilot AI retains ownership of the platform, AI models, algorithms, and all proprietary technology. Output generated by our AI for you is licensed to you for your use, but the underlying technology remains ours.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>6. Disclaimer of Legal Advice</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                LexPilot AI is a technology tool and does not provide legal advice. AI-generated outputs should always be reviewed by a qualified legal professional before reliance. We do not guarantee the accuracy, completeness, or fitness for purpose of any AI output. You acknowledge that professional judgment is required in all legal matters.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>7. Subscription & Billing</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                Paid plans are billed monthly or annually as selected. Prices are exclusive of applicable GST. Upgrades take effect immediately with prorated charges. Downgrades take effect at the next billing cycle. We reserve the right to modify pricing with 30 days advance notice.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>8. Limitation of Liability</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                To the maximum extent permitted by applicable Indian law, LexPilot AI shall not be liable for indirect, incidental, special, consequential, or punitive damages. Our total liability shall not exceed the amount paid by you for the Services in the twelve months preceding the claim.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>9. Termination</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                Either party may terminate with 30 days written notice. We may suspend access immediately for breach of these Terms. Upon termination, you may export your data within 30 days, after which it will be permanently deleted.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>10. Governing Law & Dispute Resolution</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                These Terms are governed by the laws of India. Any disputes shall be resolved through arbitration under the Arbitration and Conciliation Act, 1996, with the seat of arbitration in Bengaluru. The language of arbitration shall be English.
              </p>

              <h2 style={{ fontSize: '1.5rem', fontWeight: 700, marginTop: '2.5rem', marginBottom: '1rem', color: '#111827' }}>11. Contact</h2>
              <p style={{ marginBottom: '1.5rem' }}>
                For questions about these Terms, contact us at:<br />
                LexPilot AI Technologies Pvt. Ltd.<br />
                12th Floor, Prestige Shantiniketan<br />
                Whitefield, Bengaluru 560048<br />
                Email: legal@lexpilot.ai
              </p>
            </div>
          </motion.div>
        </div>
      </article>
    </>
  );
}
